  SERVICE_NAME: test-github-action-deployment-dev
  PROJECT_ID: risk-insight---non-prod
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/risk-insight---non-prod/test-github-action-deployment/custom-fastapi
  API_GATEWAY_CONFIG_SPEC: openapi2-run.yaml
  API_ID: test-deployment-api
  API_GATEWAY_ID: test-deployment-api-gateway
  REGION: us-central1

  TEST_VARIABLE: "alloha test 1"